name: NarouReader
configs:
  Dev: debug
  Prd: release
configFiles:
  Dev: Configs/Dev.xcconfig
  Prd: Configs/Prd.xcconfig
options:
  groupSortPosition: top

schemes:
  NarouReader:
    build:
      targets:
        NarouReader: all
        NarouReaderTests:
          - test
    run:
      config: Dev
    test:
      config: Dev
      gatherCoverageData: true
      targets:
        - NarouReaderTests
    profile:
      config: Prd
    analyze:
      config: Dev
    archive:
      config: Prd

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.2.1
  Kanna:
    url: https://github.com/tid-kijyun/Kanna.git
    from: 5.2.3
  PanModal:
    url: https://github.com/slackhq/PanModal.git
    from: 1.2.7

targets:
  NarouReader:
    type: application
    platform: iOS
    sources:
      - Configs
      - NarouReader
    settings:
      base:
        CODE_SIGN_IDENTITY: $(inherited)
        TARGETED_DEVICE_FAMILY: 1
    dependencies:
      - package: Alamofire
      - package: Kanna
      - package: PanModal

  NarouReaderTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - NarouReaderTests
    dependencies:
      - target: NarouReader